# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:1.78.0"

stages:
  - lint
  - test
  - build
  - deploy

lint-clippy:
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
  only:
    - branches
    - merge_requests

# Use cargo to test the project
test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

# Optional: Use a third party library to generate GitLab JUnit reports
# test:junit-report:
#   stage: test
#   script:
#     # Should be specified in Cargo.toml
#     - cargo install junitify
#     - cargo test -- --format=json -Z unstable-options --report-time | junitify --out $CI_PROJECT_DIR/tests/
#   artifacts:
#     when: always
#     reports:
#       junit: $CI_PROJECT_DIR/tests/*.xml

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cargo build --workspace --verbose

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
