image: "rust:1.78.0"

stages:
  - setup
  - lint
  - test
  - build
  - deploy

variables:
  PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"

setup-job:
  stage: setup
  script:
    - apt-get update
    - apt-get install -y libudev-dev pkg-config
    - find /usr -name "libudev.pc"
    - echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
    - pkg-config --libs --cflags libudev || true  
  only:
    - branches
    - merge_requests

lint-clippy:
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
  needs:
    - setup-job
  only:
    - branches
    - merge_requests

test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  
    - cargo test --workspace --verbose
  needs:
    - setup-job

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cargo build --workspace --verbose
  needs:
    - setup-job

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
  needs:
    - setup-job
