[package]
name = "ntp-daemon"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
ntp-proto = { path = "../ntp-proto" }
